# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 640273b2c50cc2700d918a11f731e691fa0376bce9ff96d9f7653624f4b71f9f8cffae881f52f09df888af30ad268821fa6c35daa1c0110ec4a705e6d448f337

test:
  secret_key_base: 8c30770c1fb0bed92aeef5b14e84e1fb3bf0bbcc99efbddd606ec7c549925cf94876e461f4e74b25bfc59d95fc1095a0e910be22d85f5c80f6b941dbdf906e89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
